name: "order_machine"
mode: "debug"
time_location: "Asia/Shanghai"

consul:
  host: "consul0"
  port: 8500

mysql:
  dsn: "root:123@tcp(mariadb0:3306)/order_machine?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai"
  max_open_conn: 20
  max_idle_conn: 10
  max_conn_life_time: 100

redis:
  addr: "redis0:6379"
  password: ""